http_port 3128

visible_hostname squid

# NOTE Allow only internal/private networks
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16

http_access allow localnet
http_access deny all

# NOTE avoid caching SSO/private pages
acl has_cookie req_header Cookie .+
acl has_auth req_header Authorization .+

cache deny has_cookie
cache deny has_auth
